// Log to console
console.log("hello world");
console.log(123);
console.log(true);
var greeting ="hello";
console.log([1,2,3,4,5]);
console.log({a:1,b:3,c:2});
console.table({a:1,b:2});
console.error("This is some error");
console.clear();
console.warn("This is a warning");
console.time("hello");
  console.log("Hello world");
  console.log("Hello world");
  console.log("Hello world");
  console.log("Hello world");
  console.log("Hello world");
  console.log("Hello world");
  console.log("Hello world");
  console.log("Hello world");
console.timeEnd("hello");